spring:
  application:
    name: cloud-workflow
eureka:
  client:
    service-url:
      defaultZone: http://user:hzjk_123@peer1:8500/eureka/,http://user:hzjk_123@peer2:8501/eureka/
  instance:
    prefer-ip-address: true
profile: dev-1.0
